# Generated by Django 4.2.5 on 2023-09-09 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_user'),
        ('user', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
