# Generated by Django 4.2.5 on 2023-09-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('MANAGER', 'Manager'), ('ADMIN', 'Admin')], default='NORMAL', max_length=10),
        ),
    ]
