# Generated by Django 4.2.5 on 2023-09-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('book', '0004_alter_book_user'),
        ('user', '0005_myuser_remove_customuser_user_ptr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.AddField(
            model_name='myuser',
            name='groups',
            field=models.ManyToManyField(related_name='myuser_groups', to='auth.group'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_permissions',
            field=models.ManyToManyField(related_name='myuser_user_permissions', to='auth.permission'),
        ),
    ]
