# Generated by Django 4.2.5 on 2023-09-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0006_delete_customuser_myuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='myuser_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='myuser_user_permissions', to='auth.permission'),
        ),
    ]
